package com.xc.rules

import java.util.Map

global Integer const1
global Integer const3


rule "rule01"
    when
      $map : Map(["B"] != 32 && ["B"] != null)
    then
     System.out.println( "rule01 , B : " + $map.get("B"));
//     $map.put("B",Integer.valueOf($map.get("B").toString()));
     $map.put("D","JAUGHUIF");
end


rule "rule02"
dialect "mvel"
    when
       $map : Map(["B"] < 32)
     then
     System.out.println( "rule02 , B : " + $map.get("B"));
     $map.put("C","Dadad");
end